### ISSUE TITLE
the gui disappears when you exit full screen and turn full screen on again 

### ISSUE THREAD

**Issue by radmanplays** [radmanplays/MeteorX-ts#6]
is there any fix?

**Comment by MegaTheLEGEND** [comment]
Does it not show up again when you press right shift? 

edit:  I just tested it myself. I think it is not working because when full screen is on it only full screens the game frame and not the whole page. so therefore its possible that your menu is actually still there it is just appearing behind the game content.

**Comment by MegaTheLEGEND** [comment]
If you put every single element under the html section into a div. Then make your menu place itself inside that div. Also some how make f11 toggle full screen for said div, it would probably work.

**Comment by leahanderson1** [comment]
gonna be fixed in 1.0

**Comment by Orphanlol** [comment]
woo hoo guys

**Comment by leahanderson1** [comment]
fixed in eaglerreborn prerelease
